'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class New_Breakdown

    '''<summary>
    '''form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''Tb_Tanggal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_Tanggal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Tb_StartAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_StartAction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Tb_FinishAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_FinishAction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Lb_Jenis1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lb_Jenis1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Cb_Jenis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cb_Jenis As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Lb_Jenis2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lb_Jenis2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Tb_Jenis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_Jenis As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Cb_Area control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cb_Area As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Cb_Modul control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cb_Modul As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Tb_Issue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_Issue As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Tb_Action control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_Action As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Tb_Improvement control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_Improvement As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Tb_Sparepart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_Sparepart As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Lb_PIC1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lb_PIC1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Cb_PIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Cb_PIC As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Lb_PIC2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lb_PIC2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Tb_PIC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_PIC As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Tb_Tambah control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Tb_Tambah As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Polman control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Polman As Global.System.Web.UI.WebControls.Image
End Class
